from __future__ import annotations

from collections.abc import AsyncIterator, Sequence
from dataclasses import dataclass
from typing import Any, Protocol
from uuid import UUID

from dms_core.config import Settings
from dms_core.models import (
    Chunk,
    Department,
    DeltaStats,
    DocumentRow,
    DocStatus,
    Folder,
    Job,
    RaptorNode,
    Stage,
    TagRef,
    TagRow,
    TagSource,
    TagStatus,
    User,
    VersionRow,
)


class BlobStore(Protocol):
    def put(self, sha256: str, data: bytes, content_type: str) -> None: ...
    def get(self, sha256: str) -> bytes: ...
    def exists(self, sha256: str) -> bool: ...
    def ensure_bucket(self) -> None: ...


class Embedder(Protocol):
    def embed(self, texts: Sequence[str]) -> list[list[float]]: ...


class Llm(Protocol):
    def complete(
        self,
        messages: list[dict[str, Any]],
        *,
        model: str | None = None,
        json_mode: bool = False,
        max_tokens: int = 800,
        temperature: float = 0.2,
    ) -> str: ...

    def stream(
        self,
        messages: list[dict[str, Any]],
        *,
        model: str | None = None,
        max_tokens: int = 1200,
        temperature: float = 0.2,
    ) -> AsyncIterator[str]: ...


class VisionOcr(Protocol):
    def transcribe(self, png_bytes: bytes, hint_lang: str | None = None) -> str: ...


class SearchIndex(Protocol):
    def ensure_indexes(self) -> None: ...
    def drop_indexes(self) -> None: ...
    def upsert_chunks(self, docs: list[dict[str, Any]]) -> None: ...
    def delete_chunks(self, chunk_ids: list[str]) -> None: ...
    def delete_document(self, document_id: str) -> None: ...
    def upsert_title(self, doc: dict[str, Any]) -> None: ...
    def search(self, index: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def msearch(self, requests: list[tuple[str, dict[str, Any]]]) -> list[dict[str, Any]]: ...
    def refresh(self) -> None: ...
    def ping(self) -> bool: ...


class Repo(Protocol):
    def ping(self) -> bool: ...

    def upsert_department(self, department_id: str, name: str) -> None: ...
    def list_departments(self, ids: list[str] | None = None) -> list[Department]: ...
    def upsert_user(self, user_id: str, username: str, display_name: str) -> None: ...
    def set_membership(self, user_id: str, department_id: str, role: str) -> None: ...
    def get_user(self, user_id: str) -> User | None: ...
    def get_user_by_username(self, username: str) -> User | None: ...

    def list_folders(self, department_ids: list[str] | None = None) -> list[Folder]: ...
    def get_folder(self, folder_id: str) -> Folder | None: ...
    def create_folder(self, name: str, parent_id: str | None = None) -> Folder: ...
    def update_folder(
        self, folder_id: str, name: str | None = None, parent_id: str | None = None, *, set_parent: bool = False
    ) -> Folder: ...
    def delete_folder(self, folder_id: str) -> None: ...
    def folder_descendants(self, folder_id: str) -> list[str]: ...
    def list_folder_documents(self, folder_ids: list[str]) -> list[DocumentRow]: ...
    def soft_delete_document(self, document_id: UUID) -> None: ...

    def create_document(
        self,
        *,
        department_id: str,
        created_by: str | None,
        title: str | None = None,
        folder_id: str | None = None,
    ) -> DocumentRow: ...
    def get_document(self, document_id: UUID) -> DocumentRow | None: ...
    def get_documents(self, ids: Sequence[UUID]) -> list[DocumentRow]: ...
    def list_documents(
        self,
        *,
        department_ids: list[str],
        doctype: str | None = None,
        tag: str | None = None,
        status: str | None = None,
        page: int = 1,
        page_size: int = 20,
        sort: str = "-created_at",
        folder_ids: list[str] | None = None,
    ) -> tuple[list[DocumentRow], int]: ...
    def list_all_document_ids(self) -> list[UUID]: ...
    def update_document(self, document_id: UUID, **fields: Any) -> DocumentRow: ...
    def set_status(self, document_id: UUID, status: DocStatus, detail: str | None = None) -> None: ...
    def find_document_by_reference(
        self, department_id: str, reference_no: str, exclude_id: UUID | None = None
    ) -> DocumentRow | None: ...

    def create_version(
        self,
        *,
        document_id: UUID,
        blob_sha256: str,
        original_filename: str,
        mime_type: str,
        size_bytes: int,
        uploaded_by: str | None,
    ) -> VersionRow: ...
    def get_version(self, version_id: UUID) -> VersionRow | None: ...
    def get_version_by_no(self, document_id: UUID, version_no: int) -> VersionRow | None: ...
    def get_current_version(self, document_id: UUID) -> VersionRow | None: ...
    def get_previous_version(self, document_id: UUID, version_no: int) -> VersionRow | None: ...
    def list_versions(self, document_id: UUID) -> list[VersionRow]: ...
    def find_version_by_sha(self, sha256: str) -> VersionRow | None: ...
    def update_version(self, version_id: UUID, **fields: Any) -> None: ...
    def set_delta_stats(self, version_id: UUID, stats: DeltaStats) -> None: ...

    def upsert_chunks(self, chunks: Sequence[Chunk]) -> None: ...
    def get_chunks(self, ids: Sequence[str]) -> list[Chunk]: ...
    def get_document_chunks(self, document_id: UUID) -> list[Chunk]: ...
    def delete_chunks(self, ids: Sequence[str]) -> None: ...
    def document_embedding(self, document_id: UUID) -> list[float] | None: ...

    def save_minhash(self, document_id: UUID, signature: bytes, bands: Sequence[tuple[int, str]]) -> None: ...
    def find_minhash_candidates(
        self, bands: Sequence[tuple[int, str]], exclude_document_id: UUID
    ) -> list[tuple[UUID, bytes]]: ...

    def list_tags(self, department_ids: list[str] | None = None) -> list[TagRow]: ...
    def get_tag(self, tag_id: int) -> TagRow | None: ...
    def get_or_create_tag(self, name: str, department_id: str | None) -> TagRow: ...
    def set_tag_centroid(self, tag_id: int, centroid: list[float] | None) -> None: ...
    def confirmed_tag_document_ids(self, tag_id: int) -> list[UUID]: ...
    def get_document_tags(self, document_id: UUID) -> list[TagRef]: ...
    def set_document_tag(
        self,
        document_id: UUID,
        tag_id: int,
        source: TagSource,
        status: TagStatus,
        similarity: float | None = None,
    ) -> None: ...
    def remove_document_tag(self, document_id: UUID, tag_id: int) -> None: ...

    def replace_raptor_nodes(self, document_id: UUID, version_no: int, nodes: Sequence[RaptorNode]) -> None: ...
    def get_raptor_nodes(self, document_id: UUID, version_no: int) -> list[RaptorNode]: ...

    def list_jobs(self, document_id: UUID) -> list[Job]: ...


class JobQueue(Protocol):
    def enqueue(self, document_id: UUID, version_id: UUID | None, stage: Stage) -> Job: ...
    def claim(self, stages: Sequence[Stage] | None = None) -> Job | None: ...
    def complete(self, job: Job) -> None: ...
    def fail(self, job: Job, error: str, max_attempts: int = 3) -> bool: ...


@dataclass
class Container:
    settings: Settings
    repo: Repo
    jobs: JobQueue
    blobs: BlobStore
    index: SearchIndex
    embedder: Embedder
    llm: Llm
    ocr: VisionOcr
